baseURL = ""
title = "Compose Docs"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true
disableKinds = [ "taxonomy", "taxonomyTerm" ]
themesDir = "themes"
publishDir = "public"

[[menu.main]]
name = "Docs"
weight = 2
url = "docs/"

[[menu.main]]
name = "Example"
weight = 3
url = "https://docs.neuralvibes.com"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
typographer = false

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
style = "monokai"
tabWidth = 2

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

[params]
repo = "https://github.com/onweru/compose"
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
enableDarkMode = true
codeMaxLines = 7
codeLineNumbers = false

  [params.logo]
  lightMode = "compose.svg"
  darkMode = "compose-light.svg"

  [params.source]
  name = "GitHub"
  icon = "github.svg"
  url = "https://github.com/onweru/compose/"

  [params.author]
  name = "Weru"
  url = "https://neuralvibes.com/author/"
